version: "3.9"

services:
  database:
    image: postgres
    container_name: database_foundtec
    restart: always
    ports: 
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=database_foundtec
      - POSTGRES_DB=foundtec
    volumes:
      - pgdata:/data/postgres


  app:
    build: .
    container_name: foundtec
    restart: always
    ports: 
      - 3333:3333
      - 9229:9229
    volumes: 
      - .:/usr/app
    links: 
      - database_foundtec
    depends_on:
      - database_foundtec



volumes:
  pgdata:
    driver: local